//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCpfCnpj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public int id { get; set; }
        public Nullable<int> fornecedor { get; set; }
        public Nullable<int> cliente { get; set; }
        public Nullable<int> material { get; set; }
        public Nullable<System.DateTime> dataVenda { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Fornecedor Fornecedor1 { get; set; }
        public virtual Material Material1 { get; set; }
    }
}
